# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeekPrice',
            fields=[
                ('surrogate_key', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('symbol', models.CharField(db_index=True, max_length=10)),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('volume', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
            ],
        ),
    ]
