# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-07 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekprice',
            name='adj_close_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
