# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0002_weekprice_adj_close_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PivotalPoint',
            fields=[
                ('surrogate_key', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('symbol', models.CharField(db_index=True, max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('state', models.CharField(max_length=50)),
                ('prev_state', models.CharField(max_length=50)),
                ('upward_trend_point', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('natural_reaction_point', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('downward_trend_point', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('natural_rally_point', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('secondary_rally_point', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('secondary_reaction_point', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
            ],
        ),
    ]
