# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_auto_20171211_0641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seasonincomestatement',
            old_name='comprehensive_income_attributable_to_owners_of_parent',
            new_name='comprehensive_income_to_non_controlling_before_combination',
        ),
        migrations.AddField(
            model_name='seasonincomestatement',
            name='comprehensive_income_to_owners_of_parent',
            field=models.DecimalField(decimal_places=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='seasonincomestatement',
            name='profit_loss_to_non_controlling_interests_before_combination',
            field=models.DecimalField(decimal_places=0, max_digits=20, null=True),
        ),
    ]
