# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_auto_20171215_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonincomestatement',
            name='total_net_change_in_provisions_for_insurance_liabilities',
            field=models.DecimalField(decimal_places=0, max_digits=20, null=True),
        ),
    ]
