# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0004_seasonincomestatement_total_net_change_in_provisions_for_insurance_liabilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonincomestatement',
            name='total_basic_earnings_per_share',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
