# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 07:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0008_seasonfinancialratio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SeasonBalanceSheet',
        ),
        migrations.DeleteModel(
            name='SeasonIncomeStatement',
        ),
    ]
