# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 07:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0010_seasonbalancesheet_seasonincomestatement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seasonincomestatement',
            old_name='ogate_key',
            new_name='surrogate_key',
        ),
    ]
