# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-28 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0012_yearcashflowstatement_yearfinancialratio_yearincomestatement'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonbalancesheet',
            name='data_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='seasoncashflowstatement',
            name='data_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='seasonfinancialratio',
            name='data_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='seasonincomestatement',
            name='data_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='yearcashflowstatement',
            name='data_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='yearfinancialratio',
            name='data_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='yearincomestatement',
            name='data_date',
            field=models.DateField(db_index=True, null=True),
        ),
    ]
