# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvgPE',
            fields=[
                ('surrogate_key', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('year', models.IntegerField(db_index=True)),
                ('date', models.DateField(db_index=True)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eps', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pe', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='VKGrowthPower',
            fields=[
                ('surrogate_key', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('year', models.IntegerField(db_index=True)),
                ('season', models.IntegerField(db_index=True)),
                ('date', models.DateField(db_index=True)),
                ('reasonable_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimate_growth_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimate_eps', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_year_eps', models.DecimalField(decimal_places=2, max_digits=10)),
                ('season_eps', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_year_season_eps', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='WawaGrowthPower',
            fields=[
                ('surrogate_key', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('year', models.IntegerField(db_index=True)),
                ('season', models.IntegerField(db_index=True)),
                ('date', models.DateField(db_index=True)),
                ('reasonable_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimate_growth_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimate_eps', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_year_eps', models.DecimalField(decimal_places=2, max_digits=10)),
                ('season_eps', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_year_season_eps', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='WawaValueLine',
            fields=[
                ('surrogate_key', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('year', models.IntegerField(db_index=True)),
                ('season', models.IntegerField(db_index=True)),
                ('date', models.DateField(db_index=True)),
                ('last_year_eps', models.DecimalField(decimal_places=2, max_digits=10)),
                ('future_eps_growth', models.DecimalField(decimal_places=2, max_digits=10)),
                ('past_pe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimate_eps', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimate_future_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimate_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hold_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_dividend', models.DecimalField(decimal_places=2, max_digits=10)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('one_low_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recovery_years', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
