# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthRevenue',
            fields=[
                ('surrogate_key', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('year', models.IntegerField(db_index=True)),
                ('month', models.IntegerField(db_index=True)),
                ('date', models.DateField(db_index=True)),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('revenue', models.DecimalField(decimal_places=0, max_digits=20, null=True)),
                ('month_growth_rate', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('last_year_revenue', models.DecimalField(decimal_places=0, max_digits=20, null=True)),
                ('year_growth_rate', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('acc_revenue', models.DecimalField(decimal_places=0, max_digits=20, null=True)),
                ('acc_year_growth_rate', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockId',
            fields=[
                ('symbol', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('market_type', models.CharField(max_length=10)),
                ('company_type', models.CharField(max_length=20)),
                ('listing_date', models.DateField()),
            ],
        ),
    ]
