# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-18 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonRevenue',
            fields=[
                ('surrogate_key', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('year', models.IntegerField(db_index=True)),
                ('season', models.IntegerField(db_index=True)),
                ('date', models.DateField(db_index=True)),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('revenue', models.DecimalField(decimal_places=0, max_digits=20, null=True)),
                ('season_growth_rate', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('last_year_revenue', models.DecimalField(decimal_places=0, max_digits=20, null=True)),
                ('acc_revenue', models.DecimalField(decimal_places=0, max_digits=20, null=True)),
                ('acc_year_growth_rate', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
