# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-28 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_updatemanagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthrevenue',
            name='data_date',
            field=models.DateField(null=True),
        ),
    ]
