# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-28 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_monthrevenue_data_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonrevenue',
            name='data_date',
            field=models.DateField(null=True),
        ),
    ]
