# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-28 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_seasonrevenue_data_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthrevenue',
            name='data_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='seasonrevenue',
            name='data_date',
            field=models.DateField(db_index=True),
        ),
    ]
