# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-29 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_auto_20180428_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonrevenue',
            name='year_growth_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
